/*
 * Copyright 2026 The RtfParserKmp contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.darkrockstudios.libs.rtfparserkmp.parser.standard

import com.darkrockstudios.libs.rtfparserkmp.parser.RtfListener
import com.darkrockstudios.libs.rtfparserkmp.rtf.Command

/**
 * Converts the events generated by an RTF parser into the single-line XML document
 * produced by the upstream RtfDumpListener, for comparison against the corpus fixtures.
 */
internal class DumpListener : RtfListener {
    private val builder = StringBuilder()

    val xml: String
        get() = builder.toString()

    override fun processDocumentStart() {
        builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
        builder.append("<rtf>")
    }

    override fun processDocumentEnd() {
        builder.append("</rtf>")
    }

    override fun processGroupStart() {
        builder.append("<group>")
    }

    override fun processGroupEnd() {
        builder.append("</group>")
    }

    override fun processBinaryBytes(data: ByteArray) {
        builder.append("<bytes>")
        for (b in data) {
            builder.append(b.toInt().toUInt().toString(16))
        }
        builder.append("</bytes>")
    }

    override fun processString(string: String) {
        builder.append("<chars>")
        builder.append(escape(string))
        builder.append("</chars>")
    }

    override fun processCommand(command: Command, parameter: Int, hasParameter: Boolean, optional: Boolean) {
        builder.append("<command name=\"")
        builder.append(command.keyword)
        builder.append("\"")
        if (hasParameter) {
            builder.append(" parameter=\"")
            builder.append(parameter)
            builder.append("\"")
        }
        if (optional) {
            builder.append(" optional=\"true\"")
        }
        builder.append("/>")
    }

    private fun escape(text: String): String {
        val out = StringBuilder(text.length)
        for (c in text) {
            when (c) {
                '&' -> out.append("&amp;")
                '<' -> out.append("&lt;")
                '>' -> out.append("&gt;")
                else -> out.append(c)
            }
        }
        return out.toString()
    }
}
